# Generated by Django 3.0.6 on 2020-06-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_course_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
